config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks, only: [:index, :show] do
    resources :actions, only: :update
  end
  root to: 'tasks#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :actions
    has_many :users, through: :actions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :llena
  has_many :actions
  has_many :tasks, through: :actions

  def llena
    Task.all.each do |task|
      @action = Action.new
      @action.user_id = self.id
      @action.task_id = task.id
      @action.finish = false
      @action.save
    end
  end
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
    before_action :authenticate_user!
    
    def update
        #@task = Task.find(params[:task_id])
        #@usuario = User.find(current_user.id)
        #@action = Action.find(task_id = @task.id, user_id = params[:user_id])
        #debugger
        @action = Action.find(params[:task_id])
        if @action.finish == false
            @action.update(finish: true)
        else
            @action.update(finish: false)
        end 
        redirect_to tasks_path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    if signed_in?
      @todos = current_user.actions
    end
  end

  def show
    @task = Task.find(params[:id])
    @ultimos = @task.actions.order('updated_at DESC').first(5)
    @usuarios = @task.actions
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolistcarro</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'tasks/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/tasks/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <%= link_to '18!', tasks_path, class: 'navbar-brand'%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <%if user_signed_in?%>
            <p><%= current_user.actions.count {|i| i.finish == true}
            %> de <%= current_user.actions.count.to_i%> tareas completadas</p>
          <%end%>
          <ul class="navbar-nav ml-auto">
            <%if user_signed_in?%>
                <li class="nav_item">
                  <p><%= current_user.email %></p>
                </li>
            <%end%>
            <% if signed_in? %>
              <li class="nav-item">
                  <%= link_to 'Cerrar sesion', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                  <%= link_to 'Iniciar sesion', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
</nav>

app/views/tasks/index.html.erb
<% if signed_in? %>
    <div class="container">
        <div class="row">
            <% @todos.each do |todo|%>
                <div class="col-md-4 p-5">
                    <div class="card" style="width: 18rem;">
                        <%= image_tag todo.task.photo, class: 'car-img-top'%>
                        <div class="card-body">
                            <h5 class="card-title"><%= todo.task.name %></h5>
                            <p class="card-text"><%= todo.task.description %></p>
                            <%= link_to 'Entrar', task_path(todo.task.id), class: 'btn btn-primary'%>
                            <%if todo.finish == false %>
                                <%= link_to 'Completar', task_action_path(todo.id, todo.task.id), method: :put, class: 'btn btn-success'%>
                            <%else%>
                                <%= link_to 'Finalizada', task_action_path(todo.id, todo.task.id), method: :put, class: 'btn btn-danger'%>
                            <%end%>
                        </div>
                    </div>
                </div>
            <%end%>
        </div>
    </div>
<% else %>
<div class="container">
        <div class="row">
            <% @tasks.each do |task|%>
                <div class="col-md-4">
                    <div class="card" style="width: 18rem;">
                        <%= image_tag task.photo, class: 'car-img-top'%>
                        <div class="card-body">
                            <h5 class="card-title"><%= task.name %></h5>
                            <p class="card-text"><%= task.description %></p>
                            <%= link_to 'Completar', task_action_path(task.id, task.id) , method: :put%>
                        </div>
                    </div>
                </div>
            <%end%>
        </div>
    </div>
<%end%>

app/views/tasks/show.html.erb
<section class = 'container'>
    <div class = 'mb-5'>
        <h1>Tarea: <%= @task.name%></h1>
    </div>
    <div class = 'row'>
        <div class = 'col-md-6'>
            <h2>Ultimos 5 usuarios en terminarla</h2>
            <div class = 'row'>
                <% @ultimos.each do |ultimo| %>
                    <% if ultimo.finish == true %>
                        <div class="col-md-6 p-5">
                            <div class="card" style="width: 13rem;">
                                <%= image_tag ultimo.user.photo, class: 'car-img-top'%>
                                <div class="card-body">
                                    <h5 class="card-title"><%= ultimo.user.name %></h5>
                                    <p class="card-text"><%= ultimo.user.email %></p>
                                </div>
                            </div>
                        </div>
                    <%end%>
                <%end%>
            </div>
        </div>
        <div class = 'col-md-6'>
            <h2>Usuarios que han completado la tarea</h2>
            <ul>
                <% @usuarios.each do |usuario| %>
                    <% if usuario.finish == true %>
                        <li>
                            <%= usuario.user.name %>
                        </li>
                    <%end%>
                <%end%>
            </ul>
        </div>
    </div>
</section>